### ISSUE TITLE
MQTT: '<=' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by HITChris** [Shmoopty/rpi-appliance-monitor#42]
Vibration.py was throwing the following exception upon calling method single() from paho.mqtt.publish -

```python
Traceback (most recent call last):
  File "/home/pi/vibration.py", line 58, in mqtt
    tls=None)
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/publish.py", line 228, in single
    protocol, transport, proxy_args)
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/publish.py", line 163, in multiple
    client.connect(hostname, port, keepalive)
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 936, in connect
    bind_address, bind_port, clean_start, properties)
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 1002, in connect_async
    if port <= 0:
TypeError: '<=' not supported between instances of 'str' and 'int'
```

I resolved this by casting the config value from string to int:

```python
mqtt_port = config.get('mqtt', 'mqtt_port')
mqtt_port = config.getint('mqtt', 'mqtt_port')
```

**Config:** 

```yaml
[mqtt]
mqtt_topic = mqtt/dryer
mqtt_hostname = 192.168.x.x
mqtt_port = 1883
mqtt_username = myuser
mqtt_password = mypass
mqtt_clientid = myuser
```

**Comment by favsto** [comment]
Hi there.
@HITChris do you figure out this issue?
I have the same error.

Thank you.

**Comment by HITChris** [comment]
> Hi there.
> @HITChris do you figure out this issue?
> I have the same error.
> 
> Thank you.

See the "I resolved this by..." part

**Comment by Shmoopty** [comment]
Thanks for the fix, @HITChris .

**Comment by MuhammadBilal1** [comment]
@HIT2022 Thank you for the fix.
**Fix:** Just send the port in INT type.
I was also getting the same issue while sending the Port # as string type.
